services:
  prob1-mysql:
    image: mysql
    container_name: prob1-mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: playground
    networks:
      - prob1-net
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  prob1-spring:
    build:
      context: ./FileUpload/playground
      dockerfile: Dockerfile
    container_name: prob1-spring-container
    depends_on:
      prob1-mysql:
        condition: service_healthy  
    networks:
      - prob1-net
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://prob1-mysql:3306/playground?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
      FLAG: FLAG{this_is_test_flag}

  prob2-flask:
    build:
      context: ./FileDownload
      dockerfile: Dockerfile
    container_name: prob2-flask-container
    networks:
      - prob2-net
    ports:
      - "5000:5000"

networks:
  prob1-net:
    driver: bridge
  prob2-net:
    driver: bridge